// Bundles backend/edge.ts into supabase/functions/apex-ai/index.js: one ES module for Supabase Edge
// Functions (Deno), committed so a deploy can import it pinned to a commit (see DEPLOY.md). openai and pg stay external as npm: imports pinned to the tested versions;
// the migrations are embedded (the function has no files to read).
import { build } from 'esbuild';
import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

const root = join(import.meta.dirname, '..');
const version = (pkg) => JSON.parse(readFileSync(join(root, 'node_modules', pkg, 'package.json'), 'utf8')).version;
const dir = join(root, 'supabase', 'migrations');
const migrations = readdirSync(dir).filter((f) => f.endsWith('.sql')).sort().map((name) => ({ name, sql: readFileSync(join(dir, name), 'utf8') }));
const outfile = join(root, 'supabase', 'functions', 'apex-ai', 'index.js');

await build({
  entryPoints: [join(root, 'backend', 'edge.ts')],
  outfile,
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: 'es2022',
  minify: process.argv.includes('--minify'),
  legalComments: 'none',
  banner: { js: '// GENERATED by `npm run ai:build:edge` from backend/edge.ts — do not edit.\nimport process from "node:process";\nimport { Buffer } from "node:buffer";' },
  define: { __dirname: '"."', __APEX_MIGRATIONS__: JSON.stringify(migrations) },
  plugins: [{
    name: 'npm-specifiers',
    setup(b) {
      b.onResolve({ filter: /^(openai|pg)(\/.*)?$/ }, ({ path }) => {
        const [, pkg, sub = ''] = path.match(/^(openai|pg)(\/.*)?$/);
        return { path: `npm:${pkg}@${version(pkg)}${sub}`, external: true };
      });
    },
  }],
});
console.log(`built ${outfile}`);
